name: Build Synkk Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./Synkk
        run: npm install

      - name: Build & Package Executable
        working-directory: ./Synkk
        run: npm run package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Synkk-Windows-Installer
          path: ./Synkk/dist-electron/*.exe
